foreground         #ebdfe6
background         #171216
cursor             #f1b3e7
cursor_text_color  #4c1f49

selection_foreground #3d2b3a
selection_background #dabfd3

color0  #171216
color8  #4e444b

color1  #ffb4ab
color9  #ffb4ab

color2  #f1b3e7
color10 #f1b3e7

color3  #f5b8a7
color11 #f5b8a7

color4  #f1b3e7
color12 #f1b3e7

color5  #dabfd3
color13 #dabfd3

color6  #f5b8a7
color14 #f5b8a7

color7  #ebdfe6
color15 #ebdfe6
