foreground         #e3e1ef
background         #12131c
cursor             #bfc2ff
cursor_text_color  #0100ac

selection_foreground #332b4b
selection_background #ccc1e9

color0  #12131c
color8  #464651

color1  #ffb4ab
color9  #ffb4ab

color2  #bfc2ff
color10 #bfc2ff

color3  #dbbaf1
color11 #dbbaf1

color4  #bfc2ff
color12 #bfc2ff

color5  #ccc1e9
color13 #ccc1e9

color6  #dbbaf1
color14 #dbbaf1

color7  #e3e1ef
color15 #e3e1ef
