foreground         #e7e0ee
background         #15121c
cursor             #d1bcff
cursor_text_color  #3d0090

selection_foreground #3c2947
selection_background #d8bde4

color0  #15121c
color8  #494550

color1  #ffb4ab
color9  #ffb4ab

color2  #d1bcff
color10 #d1bcff

color3  #eab6e5
color11 #eab6e5

color4  #d1bcff
color12 #d1bcff

color5  #d8bde4
color13 #d8bde4

color6  #eab6e5
color14 #eab6e5

color7  #e7e0ee
color15 #e7e0ee
