# Color theme from mutagen
include colors.conf

# fonts settings
font_family      JetBrainsMono Nerd Font
font_size 12

# cursor settings
cursor_trail 10
cursor_trail_decay 0.1 0.3
cursor_shape beam

# Отключение мигания (0 — курсор горит статично и не мигает)
cursor_blink_interval 0
# mouse settings
wheel_scroll_multiplier 10

# copy settings
copy_on_select yes

# Background settings
background_opacity 0.6

# pannels
hide_window_decorations yes
tab_bar_style hidden
