[config]
wallpaper_dir = "~/Pictures/Wallpaper"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/hyprland/colors.lua"
post_hook = "hyprctl reload"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.json"
output_path = "~/.config/nvim/nvim-colors.json"

[templates.sddm]
input_path = '~/.config/matugen/templates/sddm.json'
output_path = '~/.config/sddm/colors.json'

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.config/quickshell/colors.json"
