[config]
wallpaper_dir = "~/Pictures/Wallpaper"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/hyprland/colors.lua"
post_hook = "hyprctl reload"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.json"
output_path = "~/.config/nvim/nvim-colors.json"

[templates.sddm]
input_path = '~/.config/matugen/templates/sddm.json'
output_path = '~/.config/sddm/colors.json'

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.config/quickshell/colors.json"

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.telegram]
input_path = '~/.config/matugen/templates/telegram.tdesktop-theme'
output_path = '~/.config/telegram/theme.tdesktop-theme'
