-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
	hl.exec_cmd("export XDG_CURRENT_DESKTOP=Hyprland")
	hl.exec_cmd("export XDG_CURRENT_PORTAL=hyprland")
	hl.exec_cmd("qs -c Island")
	hl.exec_cmd("qs -c NotificationCenter")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("systemctl --user start hypridle")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
