source = ~/.config/hypr/colors.conf

general {
    ignore_empty_input = true
    hide_cursor = true
    fail_timeout = 500
}

background {
    path = screenshot
    blur_passes = 2
    blur_size = 5
}
shape {
    size = 100%, 100%
    color = rgba(0, 0, 0, 0.5)
    zindex = 0
}
input-field {
    size = 500, 100
    outline_thickness = 5
    dots_size = 0.3
    dots_spacing = 0.5
    dots_center = true
    fade_on_empty = false

    placeholder_text = 
    fail_text = 
    
    outer_color = $outline_variant
    inner_color = rgba(0, 0, 0 ,0)
    check_color = $outline_variant
    font_color = $primary
    fail_color = $error

    rounding = 30
}
