hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("systemctl --user start hypridle")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("qs -c Island")
	hl.exec_cmd("qs -c NotificationCenter")
	hl.exec_cmd("wl-paste --watch cliphist store")
end)
