require("hyprland/autostart")
require("hyprland/config")
require("hyprland/input")
require("hyprland/keybinds")
require("hyprland/misc")
require("hyprland/systemkeybinds")
require("hyprland/windowrules")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_CURRENT_PORTAL", "hyprland")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("XCURSOR_SIZE", "24")
