require("hyprland/autostart")
require("hyprland/config")
require("hyprland/ecosystem")
require("hyprland/input")
require("hyprland/keybinds")
require("hyprland/misc")
require("hyprland/systemkeybinds")
require("hyprland/windowrules")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_CURRENT_PORTAL", "hyprland")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "24")
