[mgr]
ratio = [0, 1, 1]
show_hidden = true
sort_by = "natural"
linemode = "size"

[preview]
max_width = 540
max_height = 960

[file]
trash = true

[opener]
nvim = [
    { run = 'nvim "%s"', block = true, desc = "Neovim" }
]

[open]
prepend_rules = [
    { mime = "text/*", use = "nvim" },
    { mime = "application/{json,javascript,typescript,xml,toml,x-shellscript}", use = "nvim" },

    { url = "*.{txt,md,json,toml,yaml,yml,ini,conf,log,sh,bash,zsh,lua,py,c,cpp,h,hpp,rs,go,js,ts,jsx,tsx,html,css,scss,sql}", use = "nvim" },
]
