add_newline = true
command_timeout = 50

format = """
$os$directory
$character"""

# minimalistic
# format = """$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold bright-red)"

[directory]
style = "bold cyan"
truncation_length = 1
truncate_to_repo = true
truncation_symbol = "…/"
home_symbol = "󰋜"

[os]
disabled = false
style = "bold blue"
format = "[$symbol]($style) "

[os.symbols]
Arch = "󰣇 "
Linux = "󰌽 "

