$on_surface = {{ colors.on_surface.default.rgba }}
$outline_variant = {{ colors.outline_variant.default. rgba}}
$error = {{ colors.error.default.rgba }}
$surface = {{ colors.surface_container.default.rgba | to_color | set_alpha: 0.65 | format: "rgba" }}
